
######################################################### FMC
set_property PACKAGE_PIN P11 [get_ports adc1_clk_ref]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_clk_ref]

set_property PACKAGE_PIN Y5 [get_ports adc2_clk_ref]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_clk_ref]

set_property PACKAGE_PIN T6 [get_ports {adc1_data_n[0]}]
set_property PACKAGE_PIN T7  [get_ports {adc1_data_p[0]}]
set_property PACKAGE_PIN L11 [get_ports {adc1_data_n[1]}]
set_property PACKAGE_PIN M11 [get_ports {adc1_data_p[1]}]
set_property PACKAGE_PIN K16 [get_ports {adc1_data_n[10]}]
set_property PACKAGE_PIN L16 [get_ports {adc1_data_p[10]}]
set_property PACKAGE_PIN N12 [get_ports {adc1_data_n[11]}]
set_property PACKAGE_PIN P12 [get_ports {adc1_data_p[11]}]
set_property PACKAGE_PIN M13 [get_ports {adc1_data_n[2]}]
set_property PACKAGE_PIN N13 [get_ports {adc1_data_p[2]}]
set_property PACKAGE_PIN K13 [get_ports {adc1_data_n[3]}]
set_property PACKAGE_PIN L13 [get_ports {adc1_data_p[3]}]
set_property PACKAGE_PIN R12 [get_ports {adc1_data_n[4]}]
set_property PACKAGE_PIN T12 [get_ports {adc1_data_p[4]}]
set_property PACKAGE_PIN M14  [get_ports {adc1_data_n[5]}]
set_property PACKAGE_PIN M15  [get_ports {adc1_data_p[5]}]
set_property PACKAGE_PIN U6 [get_ports {adc1_data_n[6]}]
set_property PACKAGE_PIN V6 [get_ports {adc1_data_p[6]}]
set_property PACKAGE_PIN V7 [get_ports {adc1_data_n[7]}]
set_property PACKAGE_PIN V8 [get_ports {adc1_data_p[7]}]
set_property PACKAGE_PIN K15  [get_ports {adc1_data_n[8]}]
set_property PACKAGE_PIN L15  [get_ports {adc1_data_p[8]}]
set_property PACKAGE_PIN U8 [get_ports {adc1_data_n[9]}]
set_property PACKAGE_PIN U9 [get_ports {adc1_data_p[9]}]
set_property PACKAGE_PIN R8 [get_ports  adc1_clk_n]
set_property PACKAGE_PIN T8 [get_ports  adc1_clk_p]
set_property PACKAGE_PIN L12 [get_ports  adc1_spi_ce]
set_property PACKAGE_PIN N11 [get_ports  adc1_spi_sclk]
set_property PACKAGE_PIN K12 [get_ports  adc1_spi_io]

set_property PACKAGE_PIN V1 [get_ports {adc2_data_n[0]}]
set_property PACKAGE_PIN V2 [get_ports {adc2_data_p[0]}]
set_property PACKAGE_PIN AA1 [get_ports {adc2_data_n[1]}]
set_property PACKAGE_PIN AA2 [get_ports {adc2_data_p[1]}]
set_property PACKAGE_PIN AA10 [get_ports {adc2_data_n[10]}]
set_property PACKAGE_PIN AA11 [get_ports {adc2_data_p[10]}]
set_property PACKAGE_PIN AC4 [get_ports {adc2_data_n[11]}]
set_property PACKAGE_PIN AB4 [get_ports {adc2_data_p[11]}]
set_property PACKAGE_PIN AC11 [get_ports {adc2_data_n[2]}]
set_property PACKAGE_PIN AC12 [get_ports {adc2_data_p[2]}]
set_property PACKAGE_PIN W6 [get_ports {adc2_data_n[3]}]
set_property PACKAGE_PIN W7 [get_ports {adc2_data_p[3]}]
set_property PACKAGE_PIN Y1 [get_ports {adc2_data_n[4]}]
set_property PACKAGE_PIN Y2 [get_ports {adc2_data_p[4]}]
set_property PACKAGE_PIN AC1 [get_ports {adc2_data_n[5]}]
set_property PACKAGE_PIN AC2 [get_ports {adc2_data_p[5]}]
set_property PACKAGE_PIN AA12 [get_ports {adc2_data_n[6]}]
set_property PACKAGE_PIN Y12 [get_ports {adc2_data_p[6]}]
set_property PACKAGE_PIN AC8 [get_ports {adc2_data_n[7]}]
set_property PACKAGE_PIN AB8 [get_ports {adc2_data_p[7]}]
set_property PACKAGE_PIN AC6 [get_ports {adc2_data_n[8]}]
set_property PACKAGE_PIN AC7 [get_ports {adc2_data_p[8]}]
set_property PACKAGE_PIN AB10 [get_ports {adc2_data_n[9]}]
set_property PACKAGE_PIN AB11 [get_ports {adc2_data_p[9]}]
set_property PACKAGE_PIN Y7 [get_ports  adc2_clk_n]
set_property PACKAGE_PIN Y8 [get_ports  adc2_clk_p]
set_property PACKAGE_PIN AA5 [get_ports  adc2_spi_ce]
set_property PACKAGE_PIN W1 [get_ports  adc2_spi_sclk]
set_property PACKAGE_PIN W2 [get_ports  adc2_spi_io]

set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_ce]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_io]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_spi_ce]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_spi_io]
set_property IOSTANDARD LVCMOS18 [get_ports adc2_spi_sclk]

set_property IOSTANDARD LVDS [get_ports {adc1_data_p[*]}]
set_property IOSTANDARD LVDS [get_ports {adc1_data_n[*]}]
set_property IOSTANDARD LVDS [get_ports adc1_clk_p]
set_property IOSTANDARD LVDS [get_ports adc1_clk_n]

set_property IOSTANDARD LVDS [get_ports {adc2_data_p[*]}]
set_property IOSTANDARD LVDS [get_ports {adc2_data_n[*]}]
set_property IOSTANDARD LVDS [get_ports adc2_clk_p]
set_property IOSTANDARD LVDS [get_ports adc2_clk_n]

